# Use postgres/example user/password credentials

services:

  api:
    container_name: api
    image: api
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080/tcp"
    environment:
      DATABASE_HOST: "${DATABASE_HOST:-postgresql}"
      DATABASE_USER: "${POSTGRES_USER:-postgres}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    entrypoint: api
    depends_on:
      postgresql:
        condition: service_started
    networks:
      - backend

  postgresql:
    container_name: postgresql
    image: postgres:18.0-alpine3.22
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-financial}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data

networks:
  backend:

volumes:
  db: